### ISSUE TITLE
(RuntimeError) Locale file :en is invalid - map key "lenient_parse" was not found

### ISSUE THREAD

**Issue by ridzria** [elixir-cldr/cldr#190] opened 2022-12-05 09:42 UTC
Hi,
I run into this error when I compile my phoenix project. I tried to delete the cache as well using following command still error . May I know what is going on?

`rm -rf priv/cldr/locales/*`

```
== Compilation error in file lib/pixerf/cldr.ex ==
** (RuntimeError) Locale file :en is invalid - map key "lenient_parse" was not found.

Generating Pxfs.Cldr for 4 locales named [:en, :id, :th, :und] with a default locale named :en

== Compilation error in file lib/pxfs/cldr.ex ==
** (RuntimeError) Locale file :en is invalid - map key "lenient_parse" was not found.
    (ex_cldr 2.34.0) lib/cldr/locale/loader.ex:201: anonymous fn/4 in Cldr.Locale.Loader.assert_valid_keys!/2
    (elixir 1.14.2) lib/enum.ex:2468: Enum."-reduce/3-lists^foldl/2-0-"/3
    (ex_cldr 2.34.0) lib/cldr/locale/loader.ex:199: Cldr.Locale.Loader.assert_valid_keys!/2
    (ex_cldr 2.34.0) lib/cldr/locale/loader.ex:128: Cldr.Locale.Loader.do_get_locale/3
    (ex_cldr 2.34.0) lib/cldr/locale/cache.ex:117: Cldr.Locale.Cache.do_get_locale/2
    (ex_cldr 2.34.0) lib/cldr/config/config.ex:2212: Cldr.Config.decimal_formats_for/2
    (elixir 1.14.2) lib/enum.ex:1658: Enum."-map/2-lists^map/1-0-"/2
    (ex_cldr 2.34.0) lib/cldr/config/config.ex:2199: Cldr.Config.decimal_format_list/1
    (ex_cldr_numbers 2.28.0) lib/cldr/number/formatter/decimal_formatter.ex:853: Cldr.Number.Formatter.Decimal.define_to_string/1
    (ex_cldr_numbers 2.28.0) lib/cldr/number/backend/decimal_formatter.ex:52: Cldr.Number.Backend.Decimal.Formatter.define_number_module/1
    (ex_cldr_numbers 2.28.0) lib/cldr/number/backend/compiler.ex:11: Cldr.Number.Backend.define_number_modules/1
    (ex_cldr 2.34.0) lib/cldr/config/config.ex:2478: anonymous fn/3 in Cldr.Config.define_provider_modules/1
    (elixir 1.14.2) lib/enum.ex:2468: Enum."-reduce/3-lists^foldl/2-0-"/3
    (ex_cldr 2.34.0) lib/cldr/config/config.ex:2476: Cldr.Config.define_provider_modules/1
    (ex_cldr 2.34.0) expanding macro: Cldr.Backend.Compiler.__before_compile__/1
    lib/pxfs/cldr.ex:1: Pxfs.Cldr (module)
```

**Comment by kipcole9** [comment] 2023-02-23 20:53
This is a duplicate of #188 (albeit with different symptoms). I am working to version the CLDR data files in the next major release in April that will force a locale download if there is a version mismatch.

**Closed by kipcole9** 2023-02-23 20:53 UTC
